### ISSUE TITLE
Error if no endgroups specified

### ISSUE THREAD

**Issue by dkozuch** [fgrunewald/Martini_PolyPly#18]
Hello,

Let me first say that this is a very cool project and I really appreciate you guys/gals for putting it together.

It does seem like there is a bug with the endgroups though. If I execute the example:

polyply -polymer PEO.martini.2 -name PEO -n_mon 10 -o PEO.itp

I get the following error:

Traceback (most recent call last):
  File "/mnt/c/Users/dkozuch/Google Drive/Debenedetti Lab/miscellaneous/Martini_PolyPly/bin/polyply", line 83, in <module>
    main()
  File "/mnt/c/Users/dkozuch/Google Drive/Debenedetti Lab/miscellaneous/Martini_PolyPly/bin/polyply", line 63, in main
    itp_tool(itp_files, args.linkfile ,args.mon, args.outfile, args.name, args.endgroup)
  File "/home/dkozuch/.local/lib/python3.6/site-packages/polyply/itp_tool/itp_I.py", line 280, in itp_tool
    new_itp = terminate(new_itp, term_info[1], offset+1)
TypeError: 'NoneType' object is not subscriptable

This can be avoided if I comment out "new_itp = terminate(...)" on line 280 of itp_l.py

Best,
Dan

**Comment by nmichelas** [comment]
Same here!

**Comment by fgrunewald** [comment]
Hey guys, 

Sorry for the bit of delay on my side, but the program actually will be replaced by a new improved version hopefully quite soon. 

Anyways, I've fixed the bug. If you run  pip3 install --upgrade git+https://github.com/fgrunewald/Martini_PolyPly.git#polyply and try it again it should work. Also check out this post in our forum for some problems that might occur:

http://cgmartini.nl/index.php/component/kunena/13-proteins/5714-pegylated-protein

Let me know if you find any other bugs or inconsistencies and I'll try my best to help. 

Cheers,
Fabian
